name: "Detector_TBC_API"
services:
  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: detector_tbc_trainer
    container_name: detector_tbc_trainer
    command: python app/entrenamiento_modelos_tb_radiografias.py
    volumes:
      - ./datos/TB_Chest_Radiography_Database:/app/datos/TB_Chest_Radiography_Database:ro
      - ./app/modelos:/app/app/modelos
    environment:
      - DATOS_PATH=/app/datos/TB_Chest_Radiography_Database
      - MODEL_OUT=/app/app/modelos

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: detector_tbc_api
    container_name: detector_tbc_api
    ports:
      - "8000:8000"
    volumes:
      - ./app/modelos:/app/app/modelos
    environment:
      - DATOS_PATH=/app/datos/TB_Chest_Radiography_Database
      - MODEL_OUT=/app/app/modelos
